### PR TITLE
Made Homepage Responsive

### PR DESCRIPTION
**Pull request by hardik7e**
## Related Issuse
- Made UI Responsive for different resolutions and mobile devices
- Added Correct Content
- Some UI Improvements on Homepage Buttons

Closes: #116 

#### Describe the changes you've made

Made Changes in hompage,js and homepage.css

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

image
image
image

### CODE REVIEW

**Comment by purnima143** [comment]
@hardik7e Hey, you wrote a lot of lines that are not needed...can u try to reduce the code lines

**Comment by hardik7e** [comment]
@purnima143 i dont see any unnecessary line of code, can you please point out

**Comment by purnima143** [comment]
@hardik7e This one is also correct...I just wanna you to think of a way to reduce the line of code...but its fine I will merge this👍🏻

**Comment by purnima143** [comment]
@hardik7e Can you resolve te conflicts so that I can merge

**Comment by hardik7e** [comment]
I resolved the conflicts

**Pull request merged**
