### PR TITLE
refactor: backend code base restructure

### PR DESCRIPTION
**Pull request by Mayank0255**
#### Describe the changes you've made

The backend code has been switched from node.ts to node.js with proper conventional setup, which will be followed throughout the api development by all the developers.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

@purnima143 Kindly add the respective labels under GSSOC'21.

### CODE REVIEW

**Comment by himanshujaidka** [comment]
there are some still modules pending which restrict us from setup the backend server

**Comment by Mayank0255** [comment]
@himanshujaidka Can you specify those modules?

**Comment by himanshujaidka** [comment]
are you able to run this on your local machine, if I trying to run this on my local machine, it is showing an error

**Comment by Mayank0255** [comment]
@himanshujaidka What error?

**Comment by himanshujaidka** [comment]
Screenshot (135)

**Comment by himanshujaidka** [comment]
Screenshot (163)

**Comment by Mayank0255** [comment]
@himanshujaidka Have you created your `.env` file as stated in `.env.example`?

**Comment by himanshujaidka** [comment]
yes

**Comment by Mayank0255** [comment]
@himanshujaidka It's a small silly mistake you are doing which is running the server by npm start, you should take a look at `package.json` everytime to look for the scripts.

Run `npm run dev` and it will work.
If it doesn't then you are missing out on some basic setup steps, as I literally just cloned again and fired up the server in just 2 mins

**Comment by himanshujaidka** [comment]
@Mayank0255 thanks, working now

**Pull request merged**
