### PR TITLE
readme updated

### PR DESCRIPTION
**Pull request by Subham142**
Closes: #493

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.(Specially for Backend)
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by codewithvk** [comment]
@Subham142  where .env.example ?

**Comment by Subham142** [comment]
sorry, I'm a bit confused, I wrote in the readme what to be on the .env file.
should I create a .en.example file with all these written on it?

**Comment by codewithvk** [comment]
> ote in the readme what to be on t

Ya you need to create .env file in the root folder and write the document accordigly.

**Comment by Subham142** [comment]
@codewithvk added the file and updated the readme accordingly  please review it

**Pull request merged**
