### PR TITLE
comments fetch action and reducer

### PR DESCRIPTION
**Pull request by Subham142**
Closes: #456 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.(Specially for Backend)
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by codewithvk** [comment]
@Subham142 Resolve conflict.

**Comment by codewithvk** [comment]
@Subham142 Resolve conflict.

**Comment by Subham142** [comment]
@codewithvk  done

**Comment by Subham142** [comment]
if you merge this one the other will again show conflict
please merge this so that I can resolve other one

**Pull request merged**
