### PR TITLE
ask question on a modal

### PR DESCRIPTION
**Pull request by Subham142**
Closes: #177 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.(Specially for Backend)
- [x] My changes generate no new warnings.

## Screenshots
Screenshot (103)

### CODE REVIEW

**Comment by codewithvk** [comment]
@Subham142 Please fill checklist of the PR template.

**Review by codewithvk — APPROVED** [review]

**Comment by Subham142** [comment]
@codewithvk  my resolve conflicts button is disabled.....
do i need to do more?

**Comment by codewithvk** [comment]
> @codewithvk my resolve conflicts button is disabled.....
> do i need to do more?
> or should i close this one and make another pr?

You can resolve conflict by run this command `git pull repolink`

**Comment by Subham142** [comment]
@codewithvk  the repo link will which one ?.my branch one or fetch upstream?... please elaborate

**Comment by codewithvk** [comment]
> @codewithvk the repo link will which one ?.my branch one or fetch upstream?... please elaborate

https://github.com/purnima143/Kurakoo.git

**Comment by Subham142** [comment]
@codewithvk  please review it

**Pull request merged**
