### PR TITLE
Changes and fixes on the Front-end homepage

### PR DESCRIPTION
**Pull request by shivamp296**
## Related Issuse

1) Login and sign-up buttons are slightly out of body.
2) The hovering effect of both of them does not comply with the orange background.
3) In side navbar - there is small gap between whatsapp and facebook icon.
4) The email box inside the footer , have send button unintended.

Closes: #504

#### Describe the changes you've made

1)Fixed the login and sign-up positioning , changed it's hover effect and also changed the text color with respect to background.
2)Fixed the gap that is in the side nav-bar and positioned it to the right for clear and transparent look.
3)Fixed the position of send button inside the e-mail textbox and edited the box itself.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.(Specially for Backend)
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| login-signup-old |  login-signup-new |
| hover-old | hover-new-2 hover-new-1 |
| Side-navbar-old | Side-navbar-new |
| email-old | email-new |

### CODE REVIEW

**Comment by codewithvk** [comment]
@shivamp296 Can you please attach screenshot with PR? also read the PR template.

**Comment by shivamp296** [comment]
> @shivamp296 Can you please attach screenshot with PR? also read the PR template.

I have attached the screenshot , please see it once. Thank you..

**Review by codewithvk — APPROVED** [review]
Looks good 🥇

**Comment by codewithvk** [comment]
@shivamp296 Could you please resolve the conflict.

**Comment by shivamp296** [comment]
> @shivamp296 Could you please resolve the conflict.

Okkk

**Comment by shivamp296** [comment]
The conflicts have been resolved and the pull request is ready to merge.

**Pull request merged**
