### PR TITLE
I added the designed pages in app.js

### PR DESCRIPTION
**Pull request by ShambhaviSharma0110**
# Related Issuse

- Info about Issue or bug

Closes: #113 

#### Describe the changes you've made
Already the navbar and homepage were made but weren't imported in the app.js or exported from their respective files

## Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
image

### CODE REVIEW

**Comment by codewithvk** [comment]
@ShambhaviSharma0110 Resolve conflict.

**Comment by ShambhaviSharma0110** [comment]
on it!

**Comment by ShambhaviSharma0110** [comment]
hey it seems to be running fine for me with my code please check

**Comment by codewithvk** [comment]
@ShambhaviSharma0110  first fetch data from the repository after You should check.

**Pull request closed without merging**
